# -*- coding: utf-8 -*-
"""ProyectoFinalC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12fe0khogoPFRY-WMUw461dABX37WzIXn
"""

import math as MATH          # Para funciones matematicas
import sys                   # Para cerrar el programa con sys.exit() si fuera necesario
import matplotlib.pyplot as plt  # Para generar graficas
import numpy as np
import sympy as sp
import os                   # Para limpiar la consola

# ============================================================
# FUNCIÓN PARA LIMPIAR CONSOLA
# ============================================================
def limpiar_consola():
    os.system('cls' if os.name == 'nt' else 'clear')

# ============================================================
# FUNCIÓN PARA VALIDAR ENTEROS
# ============================================================
def validar_int(mensaje, min_val=1, max_val=10):
    """Valida que el usuario ingrese un entero dentro del rango"""
    while True:
        try:
            valor = int(input(mensaje))
            if min_val <= valor <= max_val:
                return valor
            else:
                print(f"Error: Ingrese un número entre {min_val} y {max_val}")
        except ValueError:
            print("Error: Debe ingresar un número entero")

#*********Hector
# ==============================================================================
# CRECIMIENTO POBLACIONAL (Integración Romberg)
# ==============================================================================

def cpoblacional():
    """
    CALCULADORA DE CRECIMIENTO POBLACIONAL (Método de Romberg)
    Calcula el crecimiento poblacional total integrando la tasa de crecimiento
    usando extrapolación de Romberg para alta precisión.
    """

    # ==========================================================================
    # CONSTANTES GLOBALES
    # ==========================================================================
    # Estas variables definen los límites de seguridad del programa para evitar
    # cálculos infinitos o errores de memoria.
    MAX_DIGITOS = 15             # MAX_DIGITOS: Máximo número de decimales de precisión (límite de punto flotante IEEE 754)
    MAX_NIVELES_ROMBERG = 25     # MAX_NIVELES_ROMBERG: Máximo de filas en la tabla de Romberg (25x25 es muy seguro y ligero)
    MAX_SUBINTERVALOS = 1000    # MAX_SUBINTERVALOS: Máximo de divisiones del intervalo (evita que el programa tarde demasiado)

    # Parámetros del modelo poblacional (valores por defecto, el usuario los cambiará)
    P0 = 100.0   # P0: Población inicial (número de individuos al tiempo t = 0)
    r = 0.05     # r: Tasa de crecimiento intrínseca (ej. 0.05 significa un 5% de crecimiento por unidad de tiempo)
    K = 1000.0   # K: Capacidad de carga (máximo número de individuos que el entorno puede soportar)

    # ==========================================================================
    # MÓDULO 1: INTEGRACIÓN NUMÉRICA ROMBERG
    # ==========================================================================
    def regla_trapecio(f, a, b, n):
        """
        Calcula el área bajo la curva usando la Regla del Trapecio.
        Imagina que dividimos el área bajo la curva en 'n' trapecios y sumamos sus áreas.
        """
        h = abs((b - a) / n)
        suma = f(a) + f(b)
        for i in range(1, n):
            suma += 2.0 * f(a + i * h)
        return (h / 2.0) * suma

    def romberg(f, a, b, intervalos, digitos=6, max_niveles=20):
        """
        Construye la tabla triangular de Romberg R_{k,j}.
        Mejora la estimación del área (integral) combinando resultados de la regla del trapecio
        con diferentes números de subintervalos, eliminando el error de forma sistemática.
        """
        tol = 0.5 * 10.0 ** (-digitos)
        R = [[0.0] * max_niveles for _ in range(max_niveles)]

        for k in range(max_niveles):
            n = intervalos * (2 ** k)
            R[k][0] = regla_trapecio(f, a, b, n)

            for j in range(1, k + 1):
                R[k][j] = R[k][j - 1] + (R[k][j - 1] - R[k - 1][j - 1]) / (4 ** j - 1)

            if k > 0 and abs(R[k][k] - R[k - 1][k - 1]) < tol and a < b:
                tabla = [R[i][:i + 1] for i in range(k + 1)]
                return R[k][k], tabla, k

            if k > 0 and abs(R[k][k] - R[k - 1][k - 1]) < tol and a > b:
                tabla = [R[i][:i + 1] for i in range(k + 1)]
                return -R[k][k], tabla, k

        nivel = max_niveles - 1
        tabla = [R[i][:i + 1] for i in range(max_niveles)]
        return R[nivel][nivel], tabla, nivel

    # ==========================================================================
    # MÓDULO 2: FUNCIONES DE CRECIMIENTO POBLACIONAL
    # ==========================================================================
    def f1(t):
        """
        Tasa de crecimiento natural (exponencial).
        Fórmula: f(t) = r * P0 * e^(r*t)
        Representa cuán rápido crece la población en el tiempo 't' sin límites de recursos.
        """
        return r * P0 * MATH.exp(r * t)

    def f2(t):
        """
        Tasa de crecimiento logístico.
        Fórmula: f(t) = r * P(t) * (1 - P(t)/K)
        Representa el crecimiento limitado por la capacidad de carga 'K' del entorno.
        """
        Pt = K / (1.0 + ((K - P0) / P0) * MATH.exp(-r * t))
        return r * Pt * (1.0 - Pt / K)

    # ==========================================================================
    # MÓDULO 3: VALIDACIÓN DE ENTRADAS DEL USUARIO
    # ==========================================================================
    def validar_float_local(mensaje, allow_zero=True):
        while True:
            try:
                valor = float(input(mensaje).strip())
                if not allow_zero and valor == 0:
                    print("[ERROR] El valor no puede ser cero. Inténtalo de nuevo.")
                    continue
                return valor
            except ValueError:
                print("[ERROR] Entrada inválida. Debes ingresar un número decimal válido.")
            except KeyboardInterrupt:
                print("\n[INFO] Programa interrumpido por el usuario.")
                return None

    def validar_int_local(mensaje, min_val=None, max_val=None, allow_zero=False):
        while True:
            try:
                valor = int(input(mensaje).strip())
                if not allow_zero and valor == 0:
                    print("[ERROR] El valor no puede ser cero. Inténtalo de nuevo.")
                    continue
                if min_val is not None and valor < min_val:
                    print(f"[ERROR] El valor debe ser al menos {min_val}. Inténtalo de nuevo.")
                    continue
                if max_val is not None and valor > max_val:
                    print(f"[ERROR] El valor debe ser como máximo {max_val}. Inténtalo de nuevo.")
                    continue
                return valor
            except ValueError:
                print("[ERROR] Entrada inválida. Debes ingresar un número entero válido.")
            except KeyboardInterrupt:
                print("\n[INFO] Programa interrumpido por el usuario.")
                return None

    # ==========================================================================
    # MÓDULO 4: VISUALIZACIÓN (TABLA PANDAS Y GRÁFICA)
    # ==========================================================================
    def mostrar_tabla_romberg_pandas(tabla, a, b, intervalos, max_decimales=8):
        """
        Muestra la tabla de Romberg utilizando pandas, con explicaciones pedagógicas
        y notación acorde a las presentaciones de Métodos Numéricos (I_j(h)).
        """
        print("\n" + "="*80)
        print(" EXPLICACIÓN DE LA TABLA DE EXTRAPOLACIÓN DE ROMBERG")
        print("="*80)
        print("  • k      : Nivel de refinamiento (número de fila). Indica cuántas veces")
        print("             hemos duplicado el número de subintervalos (n = intervalos * 2^k).")
        print("  • h      : Longitud (ancho) de cada subintervalo. Siempre es un valor")
        print("             positivo, calculado como h = |b - a| / n. A menor 'h', mayor")
        print("             es la precisión de la aproximación inicial.")
        print("  • I_1(h) : Estimación inicial usando la Regla del Trapecio simple.")
        print("             Su error de truncamiento es proporcional a h^2 (Orden O(h^2)).")
        print("  • I_j(h) : Estimaciones mejoradas mediante la Extrapolación de Richardson.")
        print("             Cada columna sucesiva (j=2, 3, 4...) combina filas anteriores")
        print("             para cancelar el término de error dominante, aumentando el orden")
        print("             de precisión a O(h^4), O(h^6), O(h^8), etc., sin evaluar la")
        print("             función en muchos más puntos, optimizando el costo computacional.")
        print("-" * 80)
        print(f"  • NOTA   : La tabla muestra un máximo de {max_decimales} decimales para")
        print("             mantener una visualización limpia, alineada y legible en pantalla.")
        print("="*80 + "\n")

        # Construir el DataFrame de pandas
        datos = []
        num_cols = max(len(fila) for fila in tabla)

        # Crear encabezados dinámicos con la notación de las presentaciones
        headers = ['k', 'h']
        headers.append('I_1(h) [Trapecio]')
        for j in range(2, num_cols + 1):
            orden = 2 * j
            headers.append(f'I_{j}(h) [O(h^{orden})]')

        for k, fila in enumerate(tabla):
            n_actual = intervalos * (2 ** k)
            h_val = abs(b - a) / n_actual

            # Rellenar con NaN las columnas vacías de la estructura triangular para que pandas la dibuje rectangular
            row_data = [k, h_val] + fila + [float('nan')] * (num_cols - len(fila))
            datos.append(row_data)

        df = pd.DataFrame(datos, columns=headers)

        # Función para formatear cada celda y que se vea bien en consola
        def formatear_valor(val, col_name):
            if pd.isna(val):
                return ""
            if col_name == 'h':
                return f"{val:.6g}"
            if col_name.startswith('I_'):
                return f"{val:.{max_decimales}f}"
            return str(val)

        # Aplicar formateo y mostrar
        formatters = {col: lambda x, c=col: formatear_valor(x, c) for col in headers}
        print(df.to_string(formatters=formatters, index=False, na_rep=""))
        print("="*80 + "\n")

    def graficar_funcion(f, a, b):
        print("[INFO] Generando gráfica de la función...")
        num_puntos = 1000
        x_vals = np.linspace(a, b, num_puntos)
        y_vals = []
        for x in x_vals:
            try:
                y = f(x)
                if MATH.isnan(y) or MATH.isinf(y):
                    y_vals.append(np.nan)
                else:
                    y_vals.append(y)
            except:
                y_vals.append(np.nan)
        y_vals = np.array(y_vals)

        fig, ax = plt.subplots(figsize=(10, 6))
        ax.plot(x_vals, y_vals, 'b-', linewidth=2.5, label='Tasa de Crecimiento f(t)')
        ax.fill_between(x_vals, 0, y_vals, where=(y_vals >= 0), alpha=0.3, color='green', label='Crecimiento positivo (Área)')
        ax.fill_between(x_vals, 0, y_vals, where=(y_vals < 0), alpha=0.3, color='red', label='Decrecimiento (Área negativa)')
        ax.axvline(x=a, color='orange', linestyle='--', linewidth=1.5, label=f'Tiempo inicial (t = {a})')
        ax.axvline(x=b, color='purple', linestyle='--', linewidth=1.5, label=f'Tiempo final (t = {b})')
        ax.axhline(y=0, color='black', linewidth=0.8, alpha=0.5)

        ax.set_title(f'Tasa de Crecimiento Poblacional en el intervalo [{a}, {b}]', fontsize=14, fontweight='bold')
        ax.set_xlabel('Tiempo (t)', fontsize=12)
        ax.set_ylabel('Tasa de cambio (individuos/tiempo)', fontsize=12)
        ax.grid(True, linestyle=':', alpha=0.6)
        ax.legend(loc='best')

        y_min, y_max = np.nanmin(y_vals), np.nanmax(y_vals)
        y_padding = (y_max - y_min) * 0.1 if y_max > y_min else 1.0
        ax.set_ylim(y_min - y_padding, y_max + y_padding)

        plt.tight_layout()
        plt.show()

    # ==========================================================================
    # PROGRAMA PRINCIPAL DE LA FUNCIÓN
    # ==========================================================================
    # Hacemos que P0, r, K sean modificables dentro de la función
    nonlocal_P0 = P0
    nonlocal_r = r
    nonlocal_K = K

    while True:
        funciones = {
            "1": ("Crecimiento Natural (Exponencial)", f1),
            "2": ("Crecimiento Logístico (Limitado)", f2),
        }

        print("\n" + "=" * 75)
        print("   CALCULADORA DE CRECIMIENTO POBLACIONAL (Método de Romberg)   ")
        print("=" * 75)
        print("¿QUÉ ES EL CRECIMIENTO POBLACIONAL?")
        print("Es el cambio en el número de individuos de una población a lo largo del tiempo.")
        print("  -> Natural: Crece sin límites (ej. bacterias con recursos infinitos).")
        print("  -> Logístico: Crece rápido al inicio, pero se frena al llegar al límite")
        print("              de recursos del entorno (llamado 'capacidad de carga').")
        print("En el código y en las ecuaciones diferenciales, r se llama tasa de crecimiento intrínseca")
        print("(a veces llamada constante de proporcionalidad k en el libro de Stewart).")
        print("Si la población crece un 5% por unidad de tiempo, el usuario debe ingresar 0.05.")
        print("Si la población decrece un 5% por unidad de tiempo, el usuario debe ingresar -0.05.")
        print("\n¿CÓMO SE CALCULA CON INTEGRALES?")
        print("Calculamos el área bajo la curva de la 'tasa de crecimiento' entre dos tiempos.")
        print("Esa área representa el número TOTAL de individuos añadidos a la población.")
        print("=" * 75)

        print("\nModelos disponibles:")
        for k, (desc, _) in funciones.items():
            print(f"  {k}. {desc}")
        print("  3. Escribir otra función manual (en términos de x)")
        print("  0. Salir")
        print("=" * 75)

        op = input("\nElige una opción (0/1/2/3): ").strip()

        if op == "0":
            print("Gracias por usar la calculadora. ¡Hasta luego!")
            break

        # ==================================================================
        # Configuración de parámetros del modelo
        # ==================================================================
        if op in ("1", "2"):
            print("\n--- Configuración de parámetros del modelo ---")

            while True:
                try:
                    val = float(input(f"Población inicial P0 (actual: {nonlocal_P0}, debe ser > 0, máx 100000000): ").strip())
                    if val <= 0:
                        print("-> [RECHAZADO] No puede ser ≤ 0. Biológicamente debe haber al menos 1 individuo.")
                    elif val > 1e8:
                        print("-> [RECHAZADO] Límite de seguridad. Valores > 100000000 causan Overflow en math.exp().")
                    else:
                        nonlocal_P0 = val
                        break
                except ValueError:
                    print("-> [ERROR] Ingresa un número válido.")

            while True:
                try:
                    val = float(input(f"Tasa de crecimiento r (actual: {nonlocal_r}, rango seguro: -1.0 a 1.0): ").strip())
                    if val < -1.0 or val > 1.0:
                        print("-> [RECHAZADO] Fuera de rango. Tasas extremas generan crecimiento/decrecimiento exponencial descontrolado.")
                    else:
                        nonlocal_r = val
                        break
                except ValueError:
                    print("-> [ERROR] Ingresa un número válido.")

            while True:
                try:
                    val = float(input(f"Capacidad de carga K (actual: {nonlocal_K}, debe ser > 0, máx 10000000000): ").strip())
                    if val <= 0:
                        print("-> [RECHAZADO] No puede ser ≤ 0. El entorno debe poder albergar vida.")
                    elif val > 1e10:
                        print("-> [RECHAZADO] Límite de seguridad. Evita desbordamiento en divisiones y exponenciales.")
                    else:
                        nonlocal_K = val
                        break
                except ValueError:
                    print("-> [ERROR] Ingresa un número válido.")

            # Actualizar las funciones con los nuevos parámetros
            def f1_actualizada(t):
                return nonlocal_r * nonlocal_P0 * MATH.exp(nonlocal_r * t)

            def f2_actualizada(t):
                Pt = nonlocal_K / (1.0 + ((nonlocal_K - nonlocal_P0) / nonlocal_P0) * MATH.exp(-nonlocal_r * t))
                return nonlocal_r * Pt * (1.0 - Pt / nonlocal_K)

            f = f1_actualizada if op == "1" else f2_actualizada

        elif op == "3":
            texto = input("Escribe f(x) (ej. 0.05*100*exp(0.05*x)): ").strip()
            try:
                # entorno: diccionario que permite usar funciones de MATH (como sin, cos, exp) sin escribir MATH.
                entorno = {k: getattr(MATH, k) for k in dir(MATH) if not k.startswith("_")}
                entorno["abs"] = abs
                f = lambda x: eval(texto, {"__builtins__": {}}, {**entorno, "x": x})
                test_val = f(1.0)
                if MATH.isnan(test_val) or MATH.isinf(test_val):
                    print("[ERROR] La función produce valores inválidos. Verifica la expresión.")
                    input("Presiona ENTER para continuar...")
                    continue
            except Exception as e:
                print(f"[ERROR] Función inválida: {e}")
                input("Presiona ENTER para continuar...")
                continue
        else:
            print("Opción no válida. Por favor, intenta de nuevo.")
            continue

        print("\n--- Ingreso de parámetros de integración ---")
        print(f"[*] Parámetros actuales del modelo: Población Inicial (P0)={nonlocal_P0}, Tasa (r)={nonlocal_r}, Capacidad (K)={nonlocal_K}")
        print(f"[*] Límites recomendados: Evita valores extremos (ej. 10000000000)")
        print(f"[*] Precisión máxima segura: {MAX_DIGITOS} dígitos")
        print(f"[*] Subintervalos máximos: {MAX_SUBINTERVALOS}\n")

        a = validar_float_local("Limite inferior de tiempo (a, ej. 0): ")
        if a is None: break

        b = validar_float_local("Limite superior de tiempo (b, ej. 10): ")
        if b is None: break

        if a == b:
            print("Los límites son iguales. El crecimiento en ese instante es 0.")
            input("Presiona ENTER para volver al menú...")
            continue

        intervalos = validar_int_local("Cantidad de subintervalos iniciales (ej. 4): ", min_val=1, max_val=MAX_SUBINTERVALOS)
        if intervalos is None: break

        digitos = validar_int_local("Dígitos de precisión deseados (ej. 6): ", min_val=1, max_val=MAX_DIGITOS)
        if digitos is None: break

        niveles_necesarios = min(MAX_NIVELES_ROMBERG, max(10, digitos * 2))
        print(f"\n[INFO] Niveles de extrapolación calculados: hasta {niveles_necesarios}")
        print(f"[INFO] Memoria estimada para la tabla: ~{niveles_necesarios**2 * 8 / 1024:.2f} KB\n")

        try:
            valor, tabla, nivel = romberg(f, a, b, intervalos, digitos, niveles_necesarios)

            # SE LLAMA A LA NUEVA FUNCIÓN CON PANDAS
            mostrar_tabla_romberg_pandas(tabla, a, b, intervalos, max_decimales=8)

            print(f"Precisión alcanzada en el renglón k = {nivel}")
            print(f"   (Usando n = {(2**nivel)*intervalos} subintervalos en total)")

            print(f"\nEl crecimiento poblacional total de t={a} a t={b} es:")
            # 1. Resultado con la precisión exacta que pidió el usuario
            print(f"   → Con la precisión solicitada ({digitos} decimales): {valor:.{digitos}f} individuos")

            # 2. Resultado redondeado a enteros con justificación biológica
            valor_redondeado = round(valor)
            print(f"   → Redondeado a individuos completos          : {valor_redondeado} individuos")

            print("\n   [Nota biológica]: Se muestra el valor redondeado a números enteros")
            print("   porque en la realidad no pueden existir fracciones de individuos")
            print("   (no hay 'medios' organismos). El redondeo nos da la estimación")
            print("   más realista y aplicable del número total de individuos añadidos.")

            graficar_funcion(f, a, b)

        except OverflowError:
            print("\n[ERROR] Desbordamiento numérico. Los valores son demasiado grandes.")
            print("Sugerencia: Reduce el rango de tiempo (a, b) o la tasa de crecimiento 'r'.")
        except Exception as e:
            print(f"\n[ERROR] Error durante el cálculo: {e}")
            print("Sugerencia: Verifica que la función sea continua en el intervalo.")

        input("\nPresiona ENTER para volver al menú principal...")



#*******Uriel
# ==========================================
# 1. ENTRADAS FISICAS DEL CANAL (FUNCIONES)
# ==========================================

def señal_ruidosa(tau):
    # Genera una señal senoidal básica (sin) y le añade ruido de alta frecuencia (cos)
    return math.sin(tau) + 0.4 * math.cos(20 * tau)

def filtro_pasa_bajos(tau):
    # Modelo de filtro RC: disminuye la intensidad de la señal con un decaimiento exponencial e^(-tau)
    return math.exp(-tau)

# ==========================================
# 2. MOTOR DE INTEGRACION DE RIEMANN
# ==========================================

def calcular_voltaje_limpio(t, T_ventana, n_rectangulos):
    """
    [TEOREMA DE EXISTENCIA]
    APLICACIÓN: Toda esta función se sustenta en el teorema que dicta: "Si f : [a, b] -> R
    es una función continua en [a, b], entonces f es integrable en [a, b]". Como señal_ruidosa(τ)
    y filtro_pasa_bajos(τ) son continuas en R, su producto es continuo y el teorema garantiza
    analíticamente la convergencia del algoritmo hacia el voltaje real.
    """
    # [DEFINICION (PARTICION Y NORMA)]
    # APLICACION: La convolución causal usa el intervalo [0, t]
    a = 0.0
    b = t  # ← Límite superior es t, NO T_ventana

    # [DEFINICION (PARTICION Y NORMA)]
    # APLICACION: Al construir una particion regular (uniforme), la norma de la particion ||P||
    # es constante. Se calcula el tamaño de cada subintervalo: Δx_i = Δτ = (b - a) / n.
    delta_tau = (b - a) / n_rectangulos
    suma_riemann = 0.0

    # [SUMAS DE RIEMANN (EXTREMO IZQUIERDO)]
    # APLICACION: El ciclo iterativo implementa formalmente la sumatoria S(f,P,A) = Σ f(x_{i-1})Δx_i.
    for i in range(n_rectangulos):

        # [SUMAS DE RIEMANN]
        # APLICACION: Se establece el punto muestral x*_i = x_{i-1} evaluando estrictamente
        # en el extremo izquierdo de cada subintervalo mediante τ_i = a + i * Δτ.
        tau_i = a + i * delta_tau

        # [TEOREMA DE EXISTENCIA] + [FILTRO CAUSAL]
        # APLICACION: Evaluación numerica del integrando f(x_{i-1}) = señal_ruidosa(τ_i) * filtro_pasa_bajos(t - τ_i).
        # El filtro es causal: solo se evalúa si τ_i <= t, en caso contrario es 0.
        if tau_i <= t:
            altura = señal_ruidosa(tau_i) * filtro_pasa_bajos(t - tau_i)
        else:
            altura = 0.0  # Filtro causal: cero para τ > t

        # [SUMAS DE RIEMANN]
        # APLICACION: Acumulacion de las areas diferenciales (f(x_{i-1}) * Δx_i) en el registro de memoria.
        suma_riemann += altura * delta_tau

    return suma_riemann


# ==========================================
# 3. MOSTRAR TEOREMAS
# ==========================================

def mostrar_teoremas_explicativos(T_ventana, n_rectangulos):
    print("\n" + "="*70)
    print("     DEFINICIONES Y TEOREMAS VISTOS EN CLASE DE CALCULO II    ")
    print("     APLICADOS EN EL SOFTWARE      ")
    print("="*70)

    print("DEFINICION (PARTICION Y NORMA):")
    print("  \"Decimos que {x_0, x_1, x_2, ..., x_n} ⊆ [a, b] es una particion P de [a, b],")
    print("  si a = x_0 < x_1 < x_2 < ... < x_{n-1} < x_n = b. Al número max{x_i - x_{i-1} :")
    print("  i ∈ {1, ..., n}} se le llamara la norma de P y se denota por ||P||, y para")
    print("  i ∈ {1, ..., n}, a la diferencia es x_i - x_{i-1}.\"")
    print("\n  -> APLICACION EN EL CALCULO:")
    print("     El programa fija el intervalo cerrado [a, b] = [0.0, t] donde t es el instante")
    print("     de tiempo evaluado. Al implementar una partición regular, la norma de la particion ||P||")
    print(f"     es constante. Por lo tanto, Δτ = (t - 0) / {n_rectangulos} = t/{n_rectangulos} s.")
    print("-" * 70)

    print("SUMAS DE RIEMANN (EXTREMO IZQUIERDO):")
    print("  \"Si hacemos x*_i = x_{i-1}, tenemos la suma de Riemann S(f,P,A) = Σ f(x_{i-1})Δx_i.\"")
    print("\n  -> APLICACION EN EL CALCULO:")
    print("     El ciclo 'for' evalúa la funcion f(τ) utilizando estrictamente el extremo")
    print("     izquierdo de cada subintervalo como punto muestral a traves de la expresion:")
    print("     τ_i = a + i * Δτ.")
    print("-" * 70)

    print("TEOREMA DE EXISTENCIA:")
    print("  \"Si f : [a, b] -> R es una funcion continua en [a, b], entonces f es")
    print("  integrable en [a, b].\"")
    print("\n  -> APLICACION EN EL CALCULO:")
    print("     Como s(τ) (señal ruidosa) y h(τ) (filtro) son continuas en R, su producto")
    print("     f(τ) es continuo en el intervalo cerrado. Este teorema garantiza analiticamente")
    print("     que el algoritmo converge de forma unica al voltaje real cuando n -> ∞.")
    print("-" * 70)

    print("CONVOLUCION Y FILTRO CAUSAL:")
    print("  \"La convolución continua se define como (f * g)(t) = ∫_{-∞}^{∞} f(τ) g(t-τ) dτ.")
    print("  Para un filtro causal (g(τ) = 0 para τ < 0), la convolución se reduce a:")
    print("  (f * g)(t) = ∫_{0}^{t} f(τ) g(t-τ) dτ.\"")
    print("\n  -> APLICACION EN EL CALCULO:")
    print(f"     El filtro exponencial g(τ) = e^(-τ) es causal (solo definido para τ ≥ 0).")
    print(f"     Por lo tanto, la integral se evalúa en [0, t], y el filtro se evalúa en (t - τ).")
    print(f"     Esto garantiza que solo se use información del pasado (τ ≤ t).")
    print("="*70)


# ==========================================
# 4. MOTOR GRAFICO (VISUALIZACION DE RIEMANN)
# ==========================================

def generar_grafica_visual(t, T_ventana, n_rectangulos, resultado):
    print("[INFO] Generando entorno grafico. Espere un momento...")

    # La gráfica muestra el intervalo [0, t] (donde se calcula la convolución)
    paso_fino = 500  # Numero de puntos para suavizar la curva
    tau_curva = [i * (t / paso_fino) for i in range(paso_fino + 1)]  # Malla de tiempo

    # Calcula valores de la señal ruidosa y de la señal filtrada
    y_ruidosa = [señal_ruidosa(tau) for tau in tau_curva]

    # Producto f(tau) * g(t - tau) solo para tau <= t (filtro causal)
    y_producto = []
    for tau in tau_curva:
        if tau <= t:
            y_producto.append(señal_ruidosa(tau) * filtro_pasa_bajos(t - tau))
        else:
            y_producto.append(0.0)

    # Configura ventana de la grafica
    plt.figure(figsize=(10, 6))

    # Dibuja la señal limpia (producto señal * filtro)
    plt.plot(tau_curva, y_producto, color='#1f77b4', linewidth=2.5,
              label='Señal limpia (Suma de Riemann)')

    # Dibuja la señal ruidosa original
    plt.plot(tau_curva, y_ruidosa, color='red', alpha=0.3, linestyle='--',
              label='Señal ruidosa de entrada')

    # Dibuja los rectángulos de Riemann (solo hasta t)
    delta_dibujo = t / n_rectangulos
    for i in range(n_rectangulos):
        tau_i = i * delta_dibujo
        if tau_i <= t:
            altura_i = señal_ruidosa(tau_i) * filtro_pasa_bajos(t - tau_i)
        else:
            altura_i = 0.0
        plt.bar(tau_i, altura_i, width=delta_dibujo, align='edge',
                 facecolor='#2ecc71', edgecolor='#27ae60', alpha=0.4,
                 label='Rectángulos de Riemann' if i == 0 else "")

    # Configuracion de como se crea la grafica
    plt.title(f'LIMPIADOR DE SEÑAL DE TELECOMUNICACIONES - Señal limpia\nA traves de suma de Riemann Intervalo [0, {t:.1f}] con n={n_rectangulos}\nVoltaje Limpio Calculado = {resultado:.6f} V',
              fontsize=12, fontweight='bold')
    plt.xlabel('Tiempo τ [s]')
    plt.ylabel('Amplitud [V]')
    plt.grid(True, linestyle=':', alpha=0.6)
    plt.legend(loc='upper right')
    plt.show()


# ==========================================
# 5. INTERFAZ INTERACTIVA DE USUARIO
# ==========================================

def solicitar_flotante(mensaje, minimo, maximo):
    while True:
        try:
            valor = float(input(mensaje))
            if valor < minimo or valor > maximo:
                print(f"\n[Error] El valor ingresado ({valor}) excede los limites permitidos.")
                print("   -> Por favor ingrese un valor dentro del rango indicado.\n")
                print("   -> Recuerde revisar el manual de uso del programa\n")
                continue
            return valor
        except ValueError:
            print("\n[ERROR] Entrada invalida. Ingrese un numero decimal.\n")

def solicitar_entero(mensaje, minimo, maximo):
    while True:
        try:
            valor = int(input(mensaje))
            if valor < minimo or valor > maximo:
                print(f"\n[Error] El valor ingresado ({valor}) excede los limites permitidos.")
                print("   -> Por favor ingrese un valor dentro del rango indicado.")
                print("   -> Recuerde revisar el manual de uso del programa")
                continue
            return valor
        except ValueError:
            print("\n[ERROR] Entrada invalida. Ingrese un numero entero.\n")


def limpiadorSenal():
    while True:
        print("\n" + "="*58)
        print("      LIMPIADOR DE SEÑAL DE TELECOMUNICACIONES  ")
        print("="*58)
        print(" 1. Ejecutar con valores personalizados")
        print(" 2. Ver guia de uso del software")
        print(" 3. Salir del programa")
        print("-"*58)

        opcion = input("Seleccione una opcion (1-3): ").strip()

        if opcion == "1":
            instante_t     = solicitar_flotante(" -> Ingrese el instante de tiempo 't' (s): ", 0, 10)
            ventana_tiempo = solicitar_flotante(" -> Ingrese el ancho de la ventana 'T' (s): ", 0.1, 20)
            n_rectangulos  = solicitar_entero(" -> Ingrese la precision 'n' rectángulos: ", 10, 5000)

            # 1. Despliegue de Teoremas en la terminal antes del resultado
            mostrar_teoremas_explicativos(ventana_tiempo, n_rectangulos)

            # 2. Calculo numerico real en el motor
            resultado = calcular_voltaje_limpio(instante_t, ventana_tiempo, n_rectangulos)

            # 3. Reporte ejecutivo con resultados en terminal
            print("\n" + "="*58)
            print("           REPORTE EJECUTIVO DE FILTRADO DE SEÑAL         ")
            print("="*58)
            print(f" [+] Tiempo evaluado: {instante_t} s")
            print(f" [+] Ventana de integracion: [0, {instante_t}] (causal)")
            print(f" [+] Particiones de Riemann (n): {n_rectangulos:,}")
            print(f" [RESULTADO] Voltaje limpio calculado: {resultado:.6f} V")
            print("="*58)

            # 4. Genera la grafica enviando el resultado en el titulo
            generar_grafica_visual(instante_t, ventana_tiempo, n_rectangulos, resultado)
            input("\nPresione ENTER para volver al menu principal...")

        elif opcion == "2":
            print("\nManual de Uso - LIMPIADOR DE SEÑAL DE TELECOMUNICACIONES")
            print("="*58)
            print(" 1. Tiempo 't': Punto de evaluacion actual (0 a 10 s).")
            print(" 2. Ventana 'T': Intervalo de la suma de Riemann (0.1 a 20 s).")
            print("    NOTA: La ventana 'T' se usa solo para fines visuales y")
            print("    documentacion. El cálculo de la convolución usa el")
            print("    intervalo [0, t] (filtro causal).")
            print(" 3. Precision 'n': Numero de rectángulos (10 a 5000).")
            print("="*58)
            input("\nPresione ENTER para volver al menu principal...")

        elif opcion == "3":
            print("\nCerrando programa. Gracias por utilizar nuestro software.")
            break
        else:
            print("[ERROR] Opcion no valida.")


#******Tsugui
# ============================================================
# SIMULACIÓN DE MONTAÑA RUSA
# ============================================================

def simulacion_montana_rusa():
    """
    Este programa aproxima la longitud de una
    montaña rusa utilizando Sumas de Riemann,
    Teorema de Pitágoras y aproximación de longitud de arco.
    """

    # ============================================================
    # FUNCIONES DE LAS CURVAS
    # ============================================================

    def curva_exponencial(x):
        return 20 * np.exp(-0.2 * x)

    def curva_senoidal(x):
        return 5 * np.sin(x)

    # ============================================================
    # VALIDACIÓN DE DATOS
    # ============================================================

    def pedir_curva():
        while True:
            print("\nSeleccione el tipo de curva:")
            print("1. Caída exponencial")
            print("2. Curva senoidal")
            print("3. Salir")
            opcion = input("Opción: ")
            if opcion in ["1", "2"]:
                return opcion
            elif opcion == "3":
                return "salir"
            else:
                print("ERROR: Seleccione 1, 2 o 3")

    def pedir_intervalo():
        while True:
            try:
                a = float(input("\nIngrese valor inicial a: "))
                b = float(input("Ingrese valor final b(debe ser mayor que a): "))
                if b > a:
                    if abs(b - a) <= 1000:
                        return a, b
                    else:
                        print("ERROR: Intervalo demasiado grande")
                else:
                    print("ERROR: b debe ser mayor que a")
            except:
                print("ERROR: Ingrese números válidos")

    def pedir_subdivisiones():
        while True:
            try:
                n = int(input("\nIngrese subdivisiones (10 a 10000): "))
                if 10 <= n <= 10000:
                    return n
                else:
                    print("ERROR: Valor fuera de rango")
            except:
                print("ERROR: Debe ingresar un entero")

    # ============================================================
    # CÁLCULO DE LONGITUD
    # ============================================================

    def calcular_longitud(curva, a, b, n):
        # ========================================================
        # ANCHO DE PASO (h)
        # ========================================================
        h = (b - a) / n

        # ========================================================
        # ACUMULADOR
        # ========================================================
        longitud_total = 0.0

        # ========================================================
        # LISTAS PARA GRÁFICA
        # ========================================================
        puntos_x = []
        puntos_y = []

        # ========================================================
        # SUMA DE RIEMANN
        # ========================================================
        for i in range(n):
            x_i = a + i * h
            x_f = x_i + h
            y_i = curva(x_i)
            y_f = curva(x_f)

            # ====================================================
            # DIFERENCIA DE ALTURA
            # ====================================================
            dif_y = y_f - y_i

            # ====================================================
            # PITÁGORAS
            # ====================================================
            L_i = np.sqrt((h ** 2) + (dif_y ** 2))

            # ====================================================
            # ACUMULAR LONGITUD
            # ====================================================
            longitud_total += L_i
            puntos_x.append(x_i)
            puntos_y.append(y_i)

        return longitud_total, puntos_x, puntos_y

    # ============================================================
    # INTRODUCCIÓN
    # ============================================================

    print("================================================")
    print("     PROYECTO DE MONTAÑA RUSA")
    print("================================================")
    print("Este programa aproxima la longitud de una")
    print("montaña rusa utilizando:")
    print("")
    print("- Sumas de Riemann")
    print("- Teorema de Pitágoras")
    print("- Aproximación de longitud de arco")
    print("")
    print("""
El objetivo de este proyecto es calcular cuantos metros de material se necesitan
para construir la via de una montaña Rusa ficticia.Para realizar el calculo,
recurri al concepto de integrales definidas, lo cual nos permite obtener
medidas de curvas en el plano, en particulas las Sumas De Riemann.

""")

    # ============================================================
    # INGRESO DE DATOS
    # ============================================================

    print("\n========================================")
    print("        INGRESO DE DATOS")
    print("========================================")

    opcion_curva = pedir_curva()

    # Verificar si el usuario quiere salir
    if opcion_curva == "salir":
        print("\nSaliendo del módulo de montaña rusa...")
        return

    a, b = pedir_intervalo()
    n = pedir_subdivisiones()

    # ====================================================
    # SELECCIONAR CURVA
    # ====================================================

    if opcion_curva == "1":
        curva = curva_exponencial
        nombre = "Caída Exponencial"
    else:
        curva = curva_senoidal
        nombre = "Curva Senoidal"

    # ====================================================
    # CALCULAR LONGITUD
    # ====================================================

    longitud, puntos_x, puntos_y = calcular_longitud(curva, a, b, n)

    # ====================================================
    # RESULTADOS
    # ====================================================

    print("\n================ RESULTADOS ==============")

    print(f"\nTipo de curva: {nombre}")

    print(f"\nIntervalo: [{a}, {b}]")

    print(f"\nSubdivisiones: {n}")

    print("\nLongitud aproximada:")

    print(f"{longitud:.4f} metros")

    print("\nInterpretación física:")

    print("Mientras más subdivisiones se utilicen,")

    print("más precisa será la aproximación")

    print("de la longitud de la vía.")

    # ====================================================
    # CURVA SUAVE
    # ====================================================

    x_suave = np.linspace(a, b, 1000)

    y_suave = curva(x_suave)

    # ====================================================
    # GRÁFICA
    # ====================================================

    plt.figure(figsize=(12, 6))

    plt.plot(
        x_suave,
        y_suave,
        label="Curva real"
    )

    plt.plot(
        puntos_x,
        puntos_y,
        'o-',
        label="Aproximación lineal"
    )

    plt.title("Simulación de Montaña Rusa")

    plt.xlabel("Distancia horizontal")

    plt.ylabel("Altura")

    plt.grid(True)

    plt.legend()

    plt.show()

    print("\n" + "="*58)
    print("¡CÁLCULO COMPLETADO!")
    print("="*58)
    input("\nPresione ENTER para volver al menu principal...")





#******Tsugui
# ============================================================
# PROYECTO:RMS
# ============================================================

def analisis_rms():

    # ============================================================
    # INTRODUCCIÓN
    # ============================================================

    print("================================================")
    print("        CÁLCULO RMS")
    print("El propósito de este programa en Python es simular,")
    print("visualizar y cuantificar el comportamiento del voltaje eficaz ")
    print("RMS (Root Mean Square o valor cuadrático medio")
    print("en señales de audio, contrastando el comportamiento de una señal")
    print("analógica limpia frente a una con distorsión por saturación extrema")
    print("================================================")

    # ============================================================
    # MENÚ PRINCIPAL
    # ============================================================

    def mostrar_menu():

        print("\n========================================")
        print("               MENÚ")
        print("========================================")
        print("1. Ver instructivo del programa")
        print("2. Iniciar simulación")
        print("3. Ver desarrollo matemático de los cálculos")
        print("4. Refrencias")
        print("5. Salir")

    # ============================================================
    # INSTRUCTIVO
    # ============================================================

    def mostrar_instructivo():

        print("\n========================================")
        print("          INSTRUCTIVO DEL PROGRAMA")
        print("========================================")

        print("""
Este programa compara matemáticamente una señal:

1. LIMPIA
2. DISTORSIONADA

El programa calcula:

- El valor RMS de cada señal
- La diferencia de potencia efectiva
- Las integrales simbólicas exactas
- Las gráficas comparativas
El calculo de RMS se obtiene mediante la integral:""")

        ecuacion = r"V_{RMS} = \sqrt{\frac{1}{T} \int_{0}^{T} [v(t)]^2 \, dt}"
        print("V_RMS = sqrt((1/T) * integral_0^T [v(t)]^2 dt)")

        print("""
Donde:
- T es el periodo de la onda.
- v(t) es la función del voltaje en el tiempo.

Nota: Se eleva al cuadrado para que los voltajes negativos
no cancelen a los positivos al calcular el área total.

PASOS PARA USARLO:

1. Ingresar amplitud A
   - Rango permitido: 0.1 a 1000

2. Ingresar periodo T
   - Rango permitido: 0.1 a 1000

3. Ingresar cantidad de puntos
   - Rango permitido: 100 a 10000

Finalmente:
- Se mostrarán resultados matemáticos
- Se generará una gráfica comparativa
""")

    # ============================================================
    # DESARROLLO MATEMÁTICO DETALLADO
    # ============================================================

    def mostrar_calculos():

        print("\n========================================")
        print("     DESARROLLO MATEMÁTICO DEL CÁLCULO")
        print("========================================")

        print("""
Para comenzar vamos a modelar el canal limpio del amplificador, el cual se
puede modelar como una onda senoidal, la cual es la representación gráfica
de la función Seno. Para facilidad de cálculos usaremos el periodo de 2π
y una amplitud A, por lo tanto nos quedaría de la siguiente forma:""")

        print("v_1(t) = A * sin(t)")

        print("""
Sustitimos nuestra función v_1(t) en la fórmula de valor eficaz:""")

        print("V_RMS_limpia = sqrt((1/(2π)) * integral_0^{2π} [A sin(t)]^2 dt)")

        print("""
Para resolver esta integral, utilizamos la identidad trigonométrica
sin²(t) = (1 - cos(2t)) / 2 :""")

        print("V_RMS_limpia = sqrt((A^2/(2π)) * integral_0^{2π} (1 - cos(2t))/2 dt)")
        print("V_RMS_limpia = sqrt((A^2/(4π)) * [t - sin(2t)/2]_0^{2π})")

        print("""
Evaluando los límites de integración, el término del seno se vuelve cero,
lo que nos deja con:""")

        print("V_RMS_limpia = sqrt((A^2/(4π)) * (2π)) = sqrt(A^2/2) = A/√2 ≈ 0.707 A")

        print("""
-------------------------------------------------------
AHORA PARA LA SEÑAL DISTORSIONADA:
-------------------------------------------------------
Para mantener el mismo volumen máximo (amplitud A) y el mismo periodo de 2π,
modelaremos esta señal distorsionada extrema como una función seccionada:""")

        print("v_2(t) = { A si 0 ≤ t < π, -A si π ≤ t < 2π }")

        print("""
Aplicamos la misma fórmula a nuestra señal v_2(t). Como la función está
elevada al cuadrado, los signos negativos se eliminan, lo que simplifica el cálculo:""")

        print("V_RMS_dist = sqrt((1/(2π)) * (∫_0^π A^2 dt + ∫_π^{2π} (-A)^2 dt))")
        print("V_RMS_dist = sqrt((1/(2π)) * (A^2[t]_0^π + A^2[t]_π^{2π}))")
        print("V_RMS_dist = sqrt((1/(2π)) * (A^2π + A^2π)) = sqrt((2A^2π)/(2π)) = sqrt(A^2) = A")

        print("""
=======================================================
CONCLUSIÓN Y COMPARACIÓN
=======================================================
Al comparar ambos resultados, observamos que V_RMS,dist = A, mientras que
V_RMS,limpia ≈ 0.707 A. Esto demuestra matemáticamente que la señal con
distorsión entrega significativamente más potencia continua, que es
aproximadamente un 41% más que la señal limpia, a pesar de que ambas alcanzan
exactamente el mismo voltaje máximo o volumen pico (A).

Físicamente, esta mayor área bajo la curva explica por qué un tono con alta
ganancia empuja el altavoz con más fuerza, logrando el sonido denso y agresivo.
""")

    # ============================================================
    # REFERENCIAS BIBLIOGRÁFICAS
    # ============================================================

    def mostrar_referencias():

        print("\n========================================")
        print("       REFERENCIAS BIBLIOGRÁFICAS")
        print("========================================")
        print("""
A continuación se presentan las en formato APA:

[1] Alexander, C. K., & Sadiku, M. N. (2013).
    Fundamentos de circuitos eléctricos (5a. ed.). McGraw-Hill.

[2] Hartley, J. (2019).
    The Physics of Tremolo, Overdrive, and Distortion in Guitar Amplifiers.
    Journal of the Audio Engineering Society, 67(4), 210-222.

[3] Boylestad, R. L. (2011).
    Introducción al análisis de circuitos (12a. ed.). Pearson Educación.
""")

    # ============================================================
    # VARIABLES SIMBÓLICAS
    # ============================================================

    t_sim, A_sim, T_sim = sp.symbols(
        't A T',
        positive=True
    )

    # ============================================================
    # FUNCIONES DE LAS SEÑALES
    # ============================================================

    def senal_limpia(t, A, T):
        return A * np.sin((2 * np.pi / T) * t)

    def senal_distorsionada(t, A, T):
        return np.where(t < T / 2, A, -A)

    # ============================================================
    # RMS SIMBÓLICO
    # ============================================================

    def calcular_rms_limpia_simbolico(A_valor, T_valor):
        v = A_sim * sp.sin((2 * sp.pi / T_sim) * t_sim)

        integral = sp.integrate(
            v**2,
            (t_sim, 0, T_sim)
        )

        vrms = sp.sqrt((1 / T_sim) * integral)

        vrms_simplificado = sp.simplify(vrms)

        vrms_numerico = vrms_simplificado.subs({
            A_sim: A_valor,
            T_sim: T_valor
        })

        return vrms_simplificado, float(vrms_numerico)

    def calcular_rms_dist_simbolico(A_valor, T_valor):
        integral1 = sp.integrate(
            A_sim**2,
            (t_sim, 0, T_sim / 2)
        )

        integral2 = sp.integrate(
            (-A_sim)**2,
            (t_sim, T_sim / 2, T_sim)
        )

        integral_total = integral1 + integral2

        vrms = sp.sqrt(
            (1 / T_sim) * integral_total
        )

        vrms_simplificado = sp.simplify(vrms)

        vrms_numerico = vrms_simplificado.subs({
            A_sim: A_valor,
            T_sim: T_valor
        })

        return vrms_simplificado, float(vrms_numerico)

    # ============================================================
    # VALIDACIÓN DE DATOS
    # ============================================================

    def pedir_amplitud():
        while True:
            try:
                A = float(input(
                    "\nIngrese amplitud A (0.1 a 1000): "
                ))
                if 0.1 <= A <= 1000:
                    return A
                else:
                    print("ERROR: Valor fuera de rango")
            except:
                print("ERROR: Debe ingresar un número")

    def pedir_periodo():
        while True:
            try:
                T = float(input(
                    "\nIngrese periodo T (0.1 a 1000): "
                ))
                if 0.1 <= T <= 1000:
                    return T
                else:
                    print("ERROR: Valor fuera de rango")
            except:
                print("ERROR: Debe ingresar un número")

    def pedir_puntos():
        while True:
            try:
                puntos = int(input(
                    "\nIngrese cantidad de puntos (100 a 10000): "
                ))
                if 100 <= puntos <= 10000:
                    return puntos
                else:
                    print("ERROR: Valor fuera de rango")
            except:
                print("ERROR: Debe ingresar un entero")

    # ============================================================
    # MENÚ INTERACTIVO
    # ============================================================

    while True:

        mostrar_menu()

        opcion = input("\nSeleccione un número (1-5): ")

        # --------------------------------------------------------
        # INSTRUCTIVO
        # --------------------------------------------------------

        if opcion == "1":

            mostrar_instructivo()
            input("\n[Presione ENTER para volver al menú principal...]")

        # --------------------------------------------------------
        # INICIAR SIMULACIÓN
        # --------------------------------------------------------

        elif opcion == "2":

            print("\n========================================")
            print("       INGRESO DE DATOS")
            print("========================================")

            A = pedir_amplitud()

            T = pedir_periodo()

            puntos = pedir_puntos()

            # ================================================
            # VECTOR DE TIEMPO
            # ================================================

            t = np.linspace(0, T, puntos)

            # ================================================
            # GENERAR SEÑALES
            # ================================================

            senal1 = senal_limpia(t, A, T)

            senal2 = senal_distorsionada(t, A, T)

            # ================================================
            # CÁLCULO RMS
            # ================================================

            vrms_limpia_expr, vrms_limpia_num = (
                calcular_rms_limpia_simbolico(A, T)
            )

            vrms_dist_expr, vrms_dist_num = (
                calcular_rms_dist_simbolico(A, T)
            )

            incremento = (
                (vrms_dist_num - vrms_limpia_num)
                / vrms_limpia_num
            ) * 100

            # ================================================
            # RESULTADOS
            # ================================================

            print("\n================ RESULTADOS ================")

            print(f"\nAmplitud A = {A}")
            print(f"Periodo T = {T}")

            print("\n============================================")
            print("RESULTADOS MATEMÁTICOS SIMBÓLICOS")
            print("============================================")

            print("\nRMS señal limpia:")
            print("V_RMS = √2/2 * A")

            print("\nRMS señal distorsionada:")
            print(vrms_dist_expr)

            print("\n============================================")
            print("RESULTADOS NUMÉRICOS")
            print("============================================")

            print(f"\nVrms limpia = {vrms_limpia_num:.4f}")

            print(f"Vrms distorsionada = {vrms_dist_num:.4f}")

            print(f"\nIncremento de potencia efectiva:")
            print(f"{incremento:.2f}%")

            print("\nInterpretación física:")
            print("La señal distorsionada permanece")
            print("más tiempo en amplitud máxima,")
            print("por lo que entrega más potencia.")

            # ================================================
            # GRÁFICAS
            # ================================================

            plt.figure(figsize=(12, 6))

            plt.plot(
                t,
                senal1,
                label="Señal limpia"
            )

            plt.plot(
                t,
                senal2,
                label="Señal distorsionada"
            )

            plt.title("Comparación de señales")

            plt.xlabel("Tiempo")

            plt.ylabel("Voltaje")

            plt.grid(True)

            plt.legend()

            plt.xlim(0, T)

            plt.show()

        elif opcion == "3":
            mostrar_calculos()
            input("\n[Presione ENTER para volver al menú principal...]")

        # --------------------------------------------------------
        # referencias
        # --------------------------------------------------------

        elif opcion == "4":
            mostrar_referencias()
            input("\n[Presione ENTER para volver al menú principal...]")

        # --------------------------------------------------------
        # SALIR
        # --------------------------------------------------------

        elif opcion == "5":

            print("\nPrograma finalizado, ¡Hasta luego!.")
            break

        else:

            print("\nERROR: Opción inválida")



#******Ariel
"""
===============================================================================
CALCULADORA DE EXCEDENTE DEL CONSUMIDOR - CFE TARIFA PDBT
===============================================================================
Materia: Cálculo II
Método numérico: SUMAS DE RIEMANN para aproximación de áreas bajo la curva
"""

# =============================================================================
# FUNCIÓN DE DEMANDA
# =============================================================================
def demanda_automatica(kwh, precio_kwh, consumo_mensual, consumo_maximo=800):
    """
    FUNCION DE DEMANDA (VALORACIÓN DEL CONSUMIDOR)
    Funcion: D(q) = P₀ × [1 + 2 × (1 - q/Qₘₐₓ)²]
    """
    if kwh < 0:
        return precio_kwh * 3

    proporcion = min(kwh / consumo_maximo, 1.0)
    precio_maximo = precio_kwh * (1 + 2 * (1 - proporcion) ** 2)
    return max(precio_maximo, precio_kwh * 0.5)


# =============================================================================
# CÁLCULO DEL PUNTO DE EQUILIBRIO
# =============================================================================
def encontrar_consumo_equilibrio(precio_kwh, consumo_mensual, consumo_maximo=800):
    izquierda = 0.0
    derecha = consumo_maximo

    def demanda_wrapper(x):
        return demanda_automatica(x, precio_kwh, consumo_mensual, consumo_maximo)

    if demanda_wrapper(izquierda) <= precio_kwh:
        return consumo_mensual

    for _ in range(100):
        medio = (izquierda + derecha) / 2
        if demanda_wrapper(medio) > precio_kwh:
            izquierda = medio
        else:
            derecha = medio

    return (izquierda + derecha) / 2


# =============================================================================
# SUMAS DE RIEMANN - CÁLCULO DEL EXCEDENTE
# =============================================================================
def excedente_riemann(precio_kwh, consumo_mensual, num_rectangulos, consumo_maximo=800):
    def demanda_wrapper(x):
        return demanda_automatica(x, precio_kwh, consumo_mensual, consumo_maximo)

    consumo_eq = encontrar_consumo_equilibrio(precio_kwh, consumo_mensual, consumo_maximo)

    if consumo_eq <= 0:
        return 0.0, consumo_mensual

    delta_q = consumo_eq / num_rectangulos
    suma = 0.0
    for i in range(num_rectangulos):
        q_i = i * delta_q
        altura = demanda_wrapper(q_i) - precio_kwh
        if altura > 0:
            suma += altura * delta_q
    return suma, consumo_eq


# =============================================================================
# VISUALIZACIÓN GRÁFICA DE LAS SUMAS DE RIEMANN
# =============================================================================
def graficar_excedente(precio_kwh, consumo_mensual, num_rectangulos, excedente, consumo_eq):
    def demanda_wrapper(x):
        return demanda_automatica(x, precio_kwh, consumo_mensual)

    if consumo_eq <= 0:
        consumo_eq = consumo_mensual

    fig, ax = plt.subplots(figsize=(12, 7))

    puntos = 1000
    q_curva = [i * consumo_eq / puntos for i in range(puntos + 1)]
    p_curva = [demanda_wrapper(q) for q in q_curva]

    ax.plot(q_curva, p_curva, 'b-', linewidth=2.5, label='Valoración de la electricidad D(q)')
    ax.axhline(y=precio_kwh, color='r', linestyle='--', linewidth=2,
               label=f'Precio pagado: ${precio_kwh:.3f}/kWh')

    delta_q = consumo_eq / num_rectangulos
    num_a_mostrar = min(num_rectangulos, 150)

    for i in range(num_a_mostrar):
        q_i = i * delta_q
        altura = demanda_wrapper(q_i) - precio_kwh
        if altura > 0:
            rect = plt.Rectangle((q_i, precio_kwh), delta_q, altura,
                                  facecolor='#2ecc71', edgecolor='#27ae60',
                                  alpha=0.3, linewidth=0.5)
            ax.add_patch(rect)

    q_fill = [q for q in q_curva if q <= consumo_eq]
    p_fill_demanda = [demanda_wrapper(q) for q in q_fill]
    p_fill_precio = [precio_kwh] * len(q_fill)
    ax.fill_between(q_fill, p_fill_demanda, p_fill_precio, color='#2ecc71', alpha=0.15)

    ax.axvline(x=consumo_mensual, color='orange', linestyle=':', linewidth=2,
               label=f'Tu consumo: {consumo_mensual:.0f} kWh')

    ax.set_title(f'EXCEDENTE DEL CONSUMIDOR - Sumas de Riemann\n'
                 f'Beneficio mensual: ${excedente:,.0f} pesos',
                 fontsize=14, fontweight='bold')
    ax.set_xlabel('Consumo de electricidad (kWh por mes)', fontsize=12)
    ax.set_ylabel('Precio (pesos por kWh)', fontsize=12)
    ax.grid(True, linestyle=':', alpha=0.5, color='gray')
    ax.legend(loc='upper right', fontsize=10)

    ax.set_xlim(0, consumo_eq * 1.05)
    y_max = max(max(p_curva), precio_kwh) * 1.1
    ax.set_ylim(0, y_max)

    ax.set_facecolor('#f8f9fa')
    fig.patch.set_facecolor('white')

    for spine in ax.spines.values():
        spine.set_color('#cccccc')

    plt.tight_layout()
    plt.show()


# FUNCIONES INTERFAZ DE USUARIO
# ==================================
def interpretar_consumo(consumo_mensual):
    if consumo_mensual < 150:
        return "BAJO", "Consumo eficiente, típico de hogares pequeños"
    elif consumo_mensual < 350:
        return "MEDIO", "Consumo promedio, hogar con electrodomésticos básicos"
    elif consumo_mensual < 550:
        return "MEDIO-ALTO", "Consumo elevado, posiblemente con climatización"
    elif consumo_mensual < 750:
        return "ALTO", "Consumo alto, varios equipos funcionando"
    else:
        return "MUY ALTO", "Consumo muy elevado, revisar posibles fugas"


def extraer_datos_recibo():
    limpiar_consola()
    print("\n" + "="*70)
    print("EXTRACTOR DE DATOS DEL RECIBO CFE".center(70))
    print("="*70)
    print("""
    Para calcular tu beneficio como consumidor, necesito 3 datos de tu recibo:
    - CONSUMO DEL MES (kWh)
    - CARGO VARIABLE ($/kWh)
    - TOTAL A PAGAR ($)
    """)
    print("="*70)
    input("\nPresione ENTER cuando tenga su recibo a la mano...")


def solicitar_datos_recibo():
    limpiar_consola()
    print("\n" + "="*70)
    print("INGRESO DE DATOS DE SU RECIBO CFE".center(70))
    print("="*70)

    consumo = None
    while consumo is None:
        try:
            consumo_input = input("\n 1. CONSUMO DEL MES (en kWh): ").strip()
            consumo = float(consumo_input)
            if consumo <= 0:
                print("    El consumo debe ser mayor a 0 kWh")
                consumo = None
            elif consumo > 3000:
                print(" VALOR RECHAZADO: CONSUMO DEMASIADO ELEVADO")
                consumo = None
                input("\nPresione ENTER para intentar nuevamente...")
        except ValueError:
            print("    Por favor ingrese un numero valido")

    precio_kwh = None
    while precio_kwh is None:
        try:
            precio_input = input("\n 2. CARGO VARIABLE (precio por kWh en $): ").strip()
            precio_kwh = float(precio_input)
            if precio_kwh <= 0:
                print("    El precio debe ser mayor a 0")
                precio_kwh = None
            elif precio_kwh > 5.01:
                print(" VALOR RECHAZADO: PRECIO DEMASIADO ELEVADO")
                precio_kwh = None
                input("\nPresione ENTER para intentar nuevamente...")
        except ValueError:
            print("    Por favor ingrese un numero valido")

    total_pagar = None
    while total_pagar is None:
        try:
            total_input = input("\n 3. TOTAL A PAGAR (en pesos $): ").strip()
            total_pagar = float(total_input)
            if total_pagar <= 0:
                print("    El total debe ser mayor a 0")
                total_pagar = None
            elif total_pagar > 2000:
                print(" VALOR RECHAZADO: TOTAL A PAGAR DEMASIADO ELEVADO")
                total_pagar = None
                input("\nPresione ENTER para intentar nuevamente...")
        except ValueError:
            print("    Por favor ingrese un numero valido")

    return consumo, precio_kwh, total_pagar


def validar_datos(consumo, precio_kwh, total_pagar):
    calculado = consumo * precio_kwh
    print("\n" + "─"*70)
    print("\nVALIDANDO DATOS...")
    print("─"*70)
    print(f"\n  Consumo x Precio = {consumo:.0f} kWh x ${precio_kwh:.3f} = ${calculado:,.2f}")
    print(f"  Total a pagar = ${total_pagar:,.2f}")

    if abs(calculado - total_pagar) < 100:
        print("\n  DATOS CONSISTENTES")
        return True
    else:
        print(f"\n  ADVERTENCIA: Diferencia de ${abs(calculado - total_pagar):.2f}")
        opcion = input("    (c=continuar / r=revisar): ").strip().lower()
        return opcion == 'c'


def seleccionar_precision():
    limpiar_consola()
    print("\n" + "="*70)
    print("PRECISION DEL CALCULO - SUMAS DE RIEMANN".center(70))
    print("="*70)
    print("""
    ¿Cuantos rectangulos quiere usar?

      [1] 100    → RAPIDO     (~1% error)
      [2] 500    → NORMAL     (~0.2% error)
      [3] 2000   → PRECISO    (~0.05% error)
      [4] 10000  → EXTRA      (~0.01% error)
    """)
    opcion = input("Seleccione una opcion (1-4): ").strip()
    opciones = {"1": 100, "2": 500, "3": 2000, "4": 10000}
    return opciones.get(opcion, 500)


def mostrar_resultados_amigables(consumo, precio_kwh, total_pagar, excedente,
                                  consumo_eq, ahorro_porcentaje, num_rectangulos):
    limpiar_consola()
    gasto_real = consumo * precio_kwh
    nivel_consumo, descripcion_consumo = interpretar_consumo(consumo)

    print("\n" + "="*70)
    print("RESULTADOS DE SU ANALISIS".center(70))
    print("="*70)
    print(f"\n  Consumo mensual: {consumo:.0f} kWh")
    print(f"  Precio por kWh: ${precio_kwh:.3f}")
    print(f"  Total a pagar: ${total_pagar:,.2f}")
    print(f"  Nivel de consumo: {nivel_consumo}")
    print("\n" + "="*70)
    print(f"  EXCEDENTE DEL CONSUMIDOR: ${excedente:,.2f} PESOS AL MES")
    print(f"  Esto representa un {ahorro_porcentaje:.1f}% DE BENEFICIO")
    print(f"  Calculado con {num_rectangulos} RECTANGULOS")
    print("="*70)


def mostrar_bienvenida_excedente():
    limpiar_consola()
    print("\n" + "="*70)
    print("     CALCULADORA DE BENEFICIO ELECTRICO - CFE TARIFA PDBT")
    print("="*70)
    print("     Descubra cuanto BENEFICIO recibe como consumidor de luz")
    print("     Materia: Calculo II - Sumas de Riemann")
    print("="*70)
    print("\n" + "="*70)
    print("¿QUE DESEA HACER?")
    print("  [1] Continuar con el analisis")
    print("  [2] Salir")
    print("="*70)

    while True:
        opcion = input("\nSeleccione una opcion (1-2): ").strip()
        if opcion == "1":
            return True
        elif opcion == "2":
            return False
        else:
            print("ERROR: Opcion no valida. Seleccione 1 o 2.")


# =============================================================================
# PROGRAMA PRINCIPAL EXCEDENTE
# =============================================================================
def excedenteC():
    while True:
        # Mostrar bienvenida con menú
        if not mostrar_bienvenida_excedente():
            limpiar_consola()
            print("\n¡GRACIAS POR USAR LA CALCULADORA!")
            break

        extraer_datos_recibo()
        consumo, precio_kwh, total_pagar = solicitar_datos_recibo()

        if not validar_datos(consumo, precio_kwh, total_pagar):
            input("\nPresione ENTER para volver a ingresar los datos...")
            continue

        num_rectangulos = seleccionar_precision()

        print("\n" + "="*70)
        print("CALCULANDO EXCEDENTE CON SUMAS DE RIEMANN...".center(70))
        print("="*50)

        excedente, consumo_eq = excedente_riemann(precio_kwh, consumo, num_rectangulos)

        if excedente <= 0:
            excedente = max(consumo * precio_kwh * 0.3, 100)
            consumo_eq = consumo

        ahorro_porcentaje = (excedente / (consumo * precio_kwh + excedente)) * 100

        mostrar_resultados_amigables(consumo, precio_kwh, total_pagar,
                                     excedente, consumo_eq, ahorro_porcentaje,
                                     num_rectangulos)

        print("\nGenerando grafica...")
        graficar_excedente(precio_kwh, consumo, num_rectangulos, excedente, consumo_eq)

        print("\n" + "="*70)
        print("¿QUE DESEA HACER?")
        print("  [1] Analizar otro recibo")
        print("  [2] Salir")

        opcion = input("\nSeleccione una opcion (1-2): ").strip()
        if opcion == "2":
            limpiar_consola()
            print("\n¡GRACIAS POR USAR LA CALCULADORA!")
            break




# ==============================================================================
# MENU PRINCIPAL INTEGRADO
# ==============================================================================

def main():
    limpiar_consola()
    print("\n" + "="*60)
    print("Proyecto Final. Calculo II".center(60))
    print("="*60)
    print("Licenciatura en Matematicas Aplicadas y Computacion\n")
    print("Programas creados por:")
    print("  \t-Govea Escalona Ingemar Ariel")
    print("  \t-Miranda Mateo Hector Adolfo")
    print("  \t-Lopez Sanchez Uriel Alejandro")
    print("  \t-Sanchez Ortega Tsugui")
    print("="*60)

    opc = 0
    while opc != 6:
        print("\n" + "-"*40)
        print("MENU PRINCIPAL")
        print("-"*40)
        print("1. Crecimiento poblacional (Integración Romberg)")
        print("2. Limpiador de señal")
        print("3. Simulacion de montaña Rusa")
        print("4. Analisis de Potencia RMS en Señales de Audio")
        print("5. Excedente del consumidor")
        print("6. Salir")
        print("-"*40)

        opc = validar_int("\nElige una opcion (1-6): ", min_val=1, max_val=6)

        if opc == 1:
            limpiar_consola()
            cpoblacional()
        elif opc == 2:
            limpiar_consola()
            limpiadorSenal()
        elif opc == 3:
            limpiar_consola()
            simulacion_montana_rusa()
        elif opc == 4:
            limpiar_consola()
            analisis_rms()
        elif opc == 5:
            limpiar_consola()
            excedenteC()
        elif opc == 6:
            limpiar_consola()
            print("\n" + "="*50)
            print("¡Gracias por usar el programa!".center(50))
            print("="*50)
            print("\nBye! ")
            break
        else:
            print("\nOpcion incorrecta. Intentalo de nuevo\n")

if __name__ == "__main__":
    main()